namespace BioCore
{
    public partial class PlaySpeed : Form
    {
        /* A constructor. */
        public PlaySpeed(bool timeEnabled, bool cEnabled, int zFps, int timeFps, int cFps)
        {
            InitializeComponent();
            if (!timeEnabled)
            {
                tPlayspeed.Enabled = false;
            }
            if (!cEnabled)
            {
                cPlayspeed.Enabled = false;
            }
        }

        public int TimePlayspeed
        {
            get
            {
                return (int)tPlayspeed.Value;
            }
        }

        public int ZPlayspeed
        {
            get
            {
                return (int)zPlayspeed.Value;
            }
        }

        public int CPlayspeed
        {
            get
            {
                return (int)cPlayspeed.Value;
            }
        }

        /// When the form is closing, set the dialog result to OK
        /// 
        /// @param sender The object that raised the event.
        /// @param FormClosingEventArgs The event data generated by the FormClosing event.
        private void PlaySpeed_FormClosing(object sender, FormClosingEventArgs e)
        {
            DialogResult = DialogResult.OK;
        }
    }
}
